---
# tasks file for cisco_interface_description

- name: Gather interface facts
  cisco.nxos.nxos_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: Set interface description
  cisco.nxos.nxos_config:
    lines:
      - description {{ item['value'][0]['host'] }} via {{ item['value'][0]['port'] }}
    parents:
      - interface {{ item.key }}
  loop: "{{ ansible_facts.net_neighbors | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Save nxos
