---
# tasks file for cisco_interface_description

- name: Gather interface facts
  cisco.ios.ios_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: Set interface description
  cisco.ios.ios_config:
    lines:
      - description {{ item['value'][0]['host'] }} via {{ item['value'][0]['port'] }}
    parents:
      - interface {{ item.key }}
  when: item['value'][0]['platform'] is defined
  loop: "{{ ansible_facts.net_neighbors | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Save ios
