---
# tasks file for cisco_interface_description

- name: cisco.nxos.nxos | Gather interface facts.
  cisco.nxos.nxos_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: cisco.nxos.nxos | Set interface description.
  cisco.nxos.nxos_config:
    lines:
      - description {{ cisco_interface_description_item['value'][0]['host'] }} via {{ cisco_interface_description_item['value'][0]['port'] }}
    parents:
      - interface {{ cisco_interface_description_item.key }}
  loop: "{{ ansible_facts.net_neighbors | dict2items }}"
  loop_control:
    label: "{{ cisco_interface_description_item.key }}"
    loop_var: cisco_interface_description_item
  notify: Save nxos
